/**
 * Lint-baseline reporter.
 *
 * Runs the content-formatting lint (`lintAllContent`) once and writes a
 * per-file, per-rule snapshot to `.research/content-audit/LINT-BASELINE.md`, so
 * the content agents rewriting `content/**` can drive each count to 0. This is a
 * REPORT generator — it never edits content. Run with vite-node:
 *   vite-node scripts/lint-baseline.ts
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { lintAllContent, type LintRule } from '../src/content/validate';

const RULES: LintRule[] = ['jargon', 'bare-caret', 'table-shape', 'typo'];
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, '.research/content-audit/LINT-BASELINE.md');

const findings = lintAllContent();

/** subject = the top-level folder under content/, e.g. `mental-ability`. */
const subjectOf = (file: string): string => file.split('/')[2] ?? '(root)';

const perFile = new Map<string, Record<LintRule, number>>();
const perSubject = new Map<string, Record<LintRule, number>>();
const totals: Record<LintRule, number> = { jargon: 0, 'bare-caret': 0, 'table-shape': 0, typo: 0 };

const blank = (): Record<LintRule, number> => ({ jargon: 0, 'bare-caret': 0, 'table-shape': 0, typo: 0 });

for (const f of findings) {
  const file = perFile.get(f.file) ?? blank();
  file[f.rule] += 1;
  perFile.set(f.file, file);

  const subj = perSubject.get(subjectOf(f.file)) ?? blank();
  subj[f.rule] += 1;
  perSubject.set(subjectOf(f.file), subj);

  totals[f.rule] += 1;
}

const sum = (r: Record<LintRule, number>): number => RULES.reduce((n, k) => n + r[k], 0);
const grand = findings.length;

const row = (name: string, r: Record<LintRule, number>): string =>
  `| ${name} | ${r.jargon} | ${r['bare-caret']} | ${r['table-shape']} | ${r.typo} | **${sum(r)}** |`;

const header = '| | jargon | bare-caret | table-shape | typo | total |\n|---|---|---|---|---|---|';

const subjectRows = [...perSubject.entries()]
  .sort((a, b) => sum(b[1]) - sum(a[1]))
  .map(([s, r]) => row(s, r))
  .join('\n');

const topFiles = [...perFile.entries()]
  .sort((a, b) => sum(b[1]) - sum(a[1]))
  .slice(0, 5)
  .map(([f, r]) => row(f, r))
  .join('\n');

const allFileRows = [...perFile.entries()]
  .sort((a, b) => a[0].localeCompare(b[0]))
  .map(([f, r]) => row(f, r))
  .join('\n');

const md = `# Content-formatting lint — BASELINE

Generated by \`vite-node scripts/lint-baseline.ts\` (snapshot; content is being
rewritten concurrently). Rules: textbook **jargon** (\`iff\`, ⇔, ⇒, ∴, ∵, ≡,
\`w.r.t.\`, \`s.t.\`), **bare-caret** (exponent without braces, e.g. \`2^80\`),
**table-shape** (row/separator cell count ≠ header), **typo** (teh, recieve,
seperate, occured, acheive, untill, wich).

Drive every count to **0**; then \`npm run validate:content --strict\` passes and
the flag can be wired into \`npm run check\`.

**Grand total: ${grand} issue(s)** — jargon=${totals.jargon}, bare-caret=${totals['bare-caret']}, table-shape=${totals['table-shape']}, typo=${totals.typo}.

## Per subject
${header}
${subjectRows || '| _(none)_ | 0 | 0 | 0 | 0 | **0** |'}

## Top 5 files
${header}
${topFiles || '| _(none)_ | 0 | 0 | 0 | 0 | **0** |'}

## Per file (all ${perFile.size} file(s) with issues)
${header}
${allFileRows || '| _(none)_ | 0 | 0 | 0 | 0 | **0** |'}
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, md, 'utf8');
console.log(`Wrote ${OUT}`);
console.log(`Grand total ${grand} issue(s): jargon=${totals.jargon}, bare-caret=${totals['bare-caret']}, table-shape=${totals['table-shape']}, typo=${totals.typo}`);
